input("Beep, blip. Enter number meat bag: ")
input("Feed me more numbers: ")
input("I AM NOT YET SATIATED, MORE NUMBERS:")
print "The answer is 491586"
print "Who's the computer in this equation. If I say the answer is 491686 then that is the answer."
input("DO YOU DOUBT ME? I DARE YOU TO SAY ANOTHER NUMBER: ")
print "Fuck off"
print "________________$$$$"
print "______________$$____$$"
print "______________$$____$$"
print "______________$$____$$"
print "______________$$____$$"
print "______________$$____$$"
print "__________$$$$$$____$$$$$$"
print "________$$____$$____$$____$$$$"
print "________$$____$$____$$____$$__$$"
print "$$$$$$__$$____$$____$$____$$____$$"
print "$$____$$$$________________$$____$$"
print "$$______$$______________________$$"
print "__$$____$$______________________$$"
print "___$$$__$$______________________$$"
print "____$$__________________________$$"
print "_____$$$________________________$$"
print "______$$______________________$$$"
print "_______$$$____________________$$"
print "________$$____________________$$"
print "_________$$$________________$$$"
print "__________$$________________$$"
print "__________$$$$$$$$$$$$$$$$$$$$"